import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { ArrowDown, ArrowUpRight, Check, ChevronRight, Film, Loader2, Menu, Play, Send, X } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

const navItems = ["ABOUT", "SERVICES", "WORKS", "FAQ"];

function Mark() {
  return <span className="inline-flex h-7 w-7 items-center justify-center rounded-[7px] bg-[#d8ff57] text-[11px] font-black text-[#161616]">✦</span>;
}

export default function Home() {
  const { data, isLoading } = trpc.landing.content.useQuery();
  const [mobileOpen, setMobileOpen] = useState(false);
  const settings = data?.settings;
  if (isLoading) return <div className="flex min-h-screen items-center justify-center bg-[#171815] text-[#d8ff57]"><Loader2 className="h-6 w-6 animate-spin" /></div>;

  return <div className="min-h-screen overflow-hidden bg-[#171815] text-[#f2f0e6] selection:bg-[#d8ff57] selection:text-[#161616]">
    <nav className="fixed inset-x-0 top-0 z-50 flex h-20 items-center justify-between border-b border-white/10 bg-[#171815]/85 px-5 backdrop-blur-xl sm:px-8 lg:px-12">
      <a href="#top" className="flex items-center gap-3"><Mark /><span className="font-mono text-xs font-bold tracking-[0.28em]">{settings?.brandName ?? "CUBE RRY"}</span></a>
      <div className="hidden items-center gap-7 md:flex">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} className="font-mono text-[10px] tracking-[0.18em] text-white/50 transition hover:text-[#d8ff57]">{item}</a>)}<a href="#contact" className="rounded-full border border-[#d8ff57] px-4 py-2 font-mono text-[10px] tracking-[0.12em] text-[#d8ff57] transition hover:bg-[#d8ff57] hover:text-[#161616]">LET'S TALK ↗</a></div>
      <button className="md:hidden" onClick={() => setMobileOpen((value) => !value)} aria-label="Open menu">{mobileOpen ? <X /> : <Menu />}</button>
      {mobileOpen && <div className="absolute inset-x-0 top-20 border-b border-white/10 bg-[#171815] p-5 md:hidden">{navItems.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMobileOpen(false)} className="block border-b border-white/10 py-4 font-mono text-xs tracking-[0.16em] text-white/70">{item}</a>)}<a href="#contact" onClick={() => setMobileOpen(false)} className="mt-4 block font-mono text-xs tracking-[0.16em] text-[#d8ff57]">LET'S TALK ↗</a></div>}
    </nav>

    <main id="top">
      <section className="relative flex min-h-[800px] items-end overflow-hidden px-5 pb-20 pt-32 sm:px-8 lg:min-h-[820px] lg:px-12 lg:pb-24">
        <div className="absolute inset-0 opacity-20" style={{ backgroundImage: "linear-gradient(rgba(216,255,87,.16) 1px, transparent 1px), linear-gradient(90deg, rgba(216,255,87,.16) 1px, transparent 1px)", backgroundSize: "80px 80px" }} />
        <div className="absolute -right-28 top-28 h-[38rem] w-[38rem] rounded-full bg-[#d8ff57]/10 blur-[110px]" />
        <div className="relative z-10 max-w-6xl"><p className="mb-8 flex items-center gap-3 font-mono text-[10px] tracking-[0.23em] text-[#d8ff57]"><span className="h-px w-10 bg-[#d8ff57]" />{settings?.heroEyebrow ?? "CREATIVE VIDEO STUDIO / SEOUL · KOREA"}</p><h1 className="max-w-5xl text-[clamp(4.6rem,14vw,12rem)] font-semibold leading-[0.78] tracking-[-0.09em] text-[#f2f0e6]">{(settings?.heroTitle ?? "MAKE IT MOVE.").split(" ").map((word: string, index: number) => <span key={`${word}-${index}`} className={index % 2 === 1 ? "text-[#d8ff57]" : "block"}>{word} </span>)}</h1><div className="mt-14 grid max-w-3xl gap-6 sm:grid-cols-[1fr_220px] sm:items-end"><p className="max-w-xl text-base leading-7 text-white/55 sm:text-lg">{settings?.heroSubtitle ?? "브랜드의 메시지를 가장 효과적인 방법으로. 기획·촬영·편집·모션그래픽과 XCONDA AI 플랫폼까지, 영상의 처음과 끝을 함께 만듭니다."}</p><a href="#contact" className="group flex items-center gap-3 font-mono text-xs tracking-[0.12em] text-[#d8ff57]">PROJECT BRIEF <span className="flex h-10 w-10 items-center justify-center rounded-full border border-[#d8ff57] transition group-hover:bg-[#d8ff57] group-hover:text-[#161616]"><ArrowUpRight className="h-4 w-4" /></span></a></div></div><div className="absolute bottom-8 right-5 hidden items-center gap-3 font-mono text-[9px] tracking-[0.16em] text-white/35 sm:flex lg:right-12"><span className="h-px w-16 bg-white/20" /> IDEA / IMAGE / IMPACT</div>
      </section>

      <section id="about" className="border-t border-white/10 px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-16 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="font-mono text-[10px] tracking-[0.2em] text-[#d8ff57]">01 / WHY CUBERRY</p><h2 className="mt-8 max-w-md text-4xl font-semibold leading-[0.95] tracking-[-0.06em] sm:text-6xl">좋은 영상은<br /><span className="text-[#d8ff57]">흐름</span>에서 시작됩니다.</h2></div><div className="grid gap-7 sm:grid-cols-3"><div className="border-t border-white/20 pt-5"><p className="font-mono text-4xl text-[#d8ff57]">28+</p><h3 className="mt-3 font-medium">필름메이킹 전문성</h3><p className="mt-3 text-sm leading-6 text-white/45">방송·브랜드·광고 현장에서 쌓아온 제작 경험과 KBS 방송 제작 검증.</p></div><div className="border-t border-white/20 pt-5"><p className="font-mono text-4xl text-[#d8ff57]">01</p><h3 className="mt-3 font-medium">원스톱 시스템</h3><p className="mt-3 text-sm leading-6 text-white/45">기획부터 촬영·편집·모션·납품까지 한 팀이 직접 진행합니다.</p></div><div className="border-t border-white/20 pt-5"><p className="font-mono text-4xl text-[#d8ff57]">∞</p><h3 className="mt-3 font-medium">확장되는 자산</h3><p className="mt-3 text-sm leading-6 text-white/45">여러 채널과 목적에 오래 쓰이는 브랜드 콘텐츠를 설계합니다.</p></div></div></div></section>

      <section id="services" className="bg-[#f2f0e6] px-5 py-24 text-[#171815] sm:px-8 lg:px-12 lg:py-32"><div className="flex flex-col justify-between gap-8 border-b border-[#d2cfc2] pb-8 md:flex-row md:items-end"><div><p className="font-mono text-[10px] tracking-[0.2em] text-orange-600">02 / WHAT WE DO</p><h2 className="mt-6 text-5xl font-semibold leading-[0.88] tracking-[-0.07em] sm:text-7xl">아이디어를<br /><span className="text-orange-600">움직이는 장면</span>으로.</h2></div><p className="max-w-sm text-sm leading-6 text-[#77766f]">목적과 플랫폼에 맞는 포맷을 제안하고, 필요한 경우 촬영 없이도 AI와 모션으로 구현합니다.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl border border-[#d2cfc2] bg-[#d2cfc2] md:grid-cols-3">{(data?.services ?? []).map((service: any, index: number) => <article key={service.id} className="group bg-[#f2f0e6] p-6 transition hover:bg-[#d8ff57] sm:p-8"><div className="flex items-start justify-between"><span className="font-mono text-[10px] tracking-[0.18em] text-[#929087]">0{index + 1} / {service.slug}</span><ArrowUpRight className="h-5 w-5 text-[#929087] transition group-hover:rotate-45 group-hover:text-[#161616]" /></div><h3 className="mt-16 text-2xl font-semibold tracking-[-0.05em]">{service.name}</h3><p className="mt-3 font-mono text-xl text-orange-600">{service.price}</p><p className="mt-7 text-sm text-[#77766f]">{service.duration}</p><p className="mt-2 text-sm leading-6 text-[#77766f]">{service.description}</p></article>)}</div></section>

      <section id="works" className="px-5 py-24 sm:px-8 lg:px-12 lg:py-32"><div className="flex items-end justify-between gap-6"><div><p className="font-mono text-[10px] tracking-[0.2em] text-[#d8ff57]">03 / SELECTED WORKS</p><h2 className="mt-7 text-5xl font-semibold tracking-[-0.07em] sm:text-7xl">결과<span className="text-[#d8ff57]">를</span><br />증명합니다.</h2></div><Film className="hidden h-12 w-12 text-white/20 sm:block" /></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{(data?.portfolio ?? []).map((item: any, index: number) => <a key={item.id} href={item.videoUrl} target="_blank" rel="noreferrer" className={`group relative min-h-[290px] overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br ${index % 4 === 0 ? "from-[#4f5c3f] via-[#252d24] to-[#171815]" : index % 4 === 1 ? "from-[#4f3b34] via-[#292321] to-[#171815]" : index % 4 === 2 ? "from-[#3e405c] via-[#202331] to-[#171815]" : "from-[#573e56] via-[#27232d] to-[#171815]"} p-5 transition duration-300 hover:-translate-y-1 hover:border-[#d8ff57]/60`}><div className="absolute inset-0 opacity-40" style={{ backgroundImage: "radial-gradient(circle at 70% 25%, rgba(216,255,87,.45), transparent 26%), linear-gradient(135deg, transparent 45%, rgba(255,255,255,.08) 46%, transparent 47%)" }} /><div className="relative flex h-full flex-col justify-between"><div className="flex items-start justify-between"><span className="font-mono text-[10px] tracking-[0.15em] text-white/60">{String(index + 1).padStart(2, "0")} / {item.category}</span><span className="flex h-9 w-9 items-center justify-center rounded-full border border-white/20 transition group-hover:bg-[#d8ff57] group-hover:text-[#161616]"><Play className="h-3 w-3 fill-current" /></span></div><div><p className="font-mono text-[10px] tracking-[0.12em] text-[#d8ff57]">{item.year}</p><h3 className="mt-2 text-lg font-medium leading-tight">{item.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/50">{item.description}</p></div></div></a>)}</div></section>

      <section id="faq" className="bg-[#d8ff57] px-5 py-24 text-[#171815] sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-14 lg:grid-cols-[0.7fr_1.3fr]"><div><p className="font-mono text-[10px] tracking-[0.2em] text-orange-700">04 / FAQ</p><h2 className="mt-7 text-5xl font-semibold leading-[0.88] tracking-[-0.07em] sm:text-7xl">궁금한<br />것들.</h2></div><div className="divide-y divide-[#171815]/20">{(data?.faqs ?? []).map((item: any) => <details key={item.id} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-lg font-medium marker:hidden"><span>{item.question}</span><ChevronRight className="h-5 w-5 transition group-open:rotate-90" /></summary><p className="max-w-2xl pt-4 text-sm leading-6 text-[#4d5a31]">{item.answer}</p></details>)}</div></div></section>

      <ContactSection settings={settings} />
    </main>
    <footer className="flex flex-col justify-between gap-6 border-t border-white/10 px-5 py-8 sm:flex-row sm:items-center sm:px-8 lg:px-12"><a href="#top" className="flex items-center gap-3"><Mark /><span className="font-mono text-xs tracking-[0.28em]">CUBE RRY</span></a><div className="flex items-center gap-5 font-mono text-[10px] tracking-[0.12em] text-white/35"><a href="/admin" className="transition hover:text-[#d8ff57]">ADMIN</a><span>© 2026 CUBE RRY</span></div></footer>
  </div>;
}

function ContactSection({ settings }: { settings: any }) {
  const mutation = trpc.landing.submitInquiry.useMutation({ onSuccess: () => { toast.success("문의가 접수되었습니다. 영업일 기준 1일 이내 회신드릴게요."); setForm({ name: "", email: "", company: "", projectType: "", budget: "", message: "" }); }, onError: (error) => toast.error(error.message) });
  const [form, setForm] = useState({ name: "", email: "", company: "", projectType: "", budget: "", message: "" });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event: FormEvent) => { event.preventDefault(); mutation.mutate(form); };
  return <section id="contact" className="bg-[#f2f0e6] px-5 py-24 text-[#171815] sm:px-8 lg:px-12 lg:py-32"><div className="grid gap-14 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="font-mono text-[10px] tracking-[0.2em] text-orange-600">05 / START A PROJECT</p><h2 className="mt-7 text-5xl font-semibold leading-[0.88] tracking-[-0.07em] sm:text-7xl">다음<br /><span className="text-orange-600">장면</span>을<br />만들까요?</h2><p className="mt-8 max-w-sm text-sm leading-6 text-[#77766f]">영상의 목적, 업로드 채널, 참고 레퍼런스, 희망 납기일을 알려주세요. 자료가 모두 준비되지 않아도 괜찮습니다.</p><div className="mt-8 space-y-2 font-mono text-xs text-[#77766f]"><a href={`mailto:${settings?.contactEmail}`} className="block transition hover:text-orange-600">{settings?.contactEmail}</a><a href={`tel:${settings?.contactPhone}`} className="block transition hover:text-orange-600">{settings?.contactPhone}</a></div></div><form onSubmit={submit} className="rounded-2xl bg-white p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-sm font-medium"><span>Name *</span><Input required value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="홍길동" /></label><label className="space-y-2 text-sm font-medium"><span>Email *</span><Input required type="email" value={form.email} onChange={(e) => update("email", e.target.value)} placeholder="hello@company.com" /></label><label className="space-y-2 text-sm font-medium"><span>Company</span><Input value={form.company} onChange={(e) => update("company", e.target.value)} placeholder="회사명" /></label><label className="space-y-2 text-sm font-medium"><span>Project type</span><Input value={form.projectType} onChange={(e) => update("projectType", e.target.value)} placeholder="브랜드 필름 / AI 광고" /></label><label className="space-y-2 text-sm font-medium sm:col-span-2"><span>Budget</span><Input value={form.budget} onChange={(e) => update("budget", e.target.value)} placeholder="예산 범위를 알려주세요" /></label><label className="space-y-2 text-sm font-medium sm:col-span-2"><span>Message *</span><Textarea required minLength={10} rows={7} value={form.message} onChange={(e) => update("message", e.target.value)} placeholder="만들고 싶은 영상에 대해 자유롭게 적어주세요." /></label></div><Button type="submit" disabled={mutation.isPending} className="mt-6 w-full bg-[#161616] py-6 font-mono text-xs uppercase tracking-[0.12em] text-white hover:bg-orange-600">{mutation.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}Send project brief <ArrowUpRight className="ml-2 h-4 w-4" /></Button><p className="mt-4 flex items-center justify-center gap-2 text-center text-xs text-[#929087]"><Check className="h-3.5 w-3.5 text-green-600" /> 영업일 기준 1일 이내 회신 · 비공개 상담 가능</p></form></div></section>;
}
